### ISSUE TITLE
config.dart is missing from Example

### ISSUE THREAD

**Issue by dhemminger-bc** [hokamc/google_drive_client#2]
Main.dart includes the following import statement (import 'package:example/config.dart';), but there is no config.dart at that location.  This causes an undefined error at the following line of code.

  (14)  final GoogleDriveClient client = GoogleDriveClient(Dio(), getAccessToken: () async => Config.ACCESS_TOKEN);

**Comment by hokamc** [comment]
feel free to add your own Config.ACCESS_TOKEN.
