### ISSUE TITLE
DioError [DioErrorType.RESPONSE]: Http status error [403]

### ISSUE THREAD

**Issue by ArjanAswal** [hokamc/google_drive_client#3]
```
var client = await GoogleDriveClient(Dio(), getAccessToken: () async => await _googleSignIn.currentUser.authentication.then((value) => value.accessToken));

await print(await client.list());
```

The above code shows this error : 
`DioError [DioErrorType.RESPONSE]: Http status error [403]`

I have enabled the google drive API for the project and also requested the google drive scope for signing in.
Any idea what to do?

**Comment by hokamc** [comment]
You may not write "then" if you are returning result directly.

```
(await _googleSignIn.currentUser.authentication).accessToken
```

**Comment by ArjanAswal** [comment]
I pasted the accessToken directly.

```
var client = await GoogleDriveClient(Dio(), getAccessToken: () async => 'xxxxxxxx');

await print(await client.list());
```

This is not working as well.

**Comment by hokamc** [comment]
It is better if you can provide the error message.
Also, you can refer to google api doc for debugging. [Drive API Error](https://developers.google.com/drive/api/v3/handle-errors)
Please you make sure that you have configured your google sign in correctly.

**Comment by ArjanAswal** [comment]
> It is better if you can provide the error message.

`DioError [DioErrorType.RESPONSE]: Http status error [403]`

> Please you make sure that you have configured your google sign in correctly.

The google sign-in is working fine. I am able to receive the access token. 

> Also, you can refer to google api doc for debugging. [Drive API Error](https://developers.google.com/drive/api/v3/handle-errors)

It is a 403 error. Currently looking at it.

**Comment by ArjanAswal** [comment]
Having tried another [method](https://medium.com/better-programming/the-minimum-guide-for-using-google-drive-api-with-flutter-9207e4cb05ba). I have found that you also have to pass auth headers with the request. In your package, only an access token is being passed. And that is insufficient.
